version: '3'
services:
  timezonefinder_app:
    container_name: timezonefinder_app
    build:
      context: .
      dockerfile: .docker/Dockerfile
    image: timezonefinder_app
    restart: always
    ports:
      - "8082:8000"

  raw_script:
    container_name: raw_script
    build:
      context: .
      dockerfile: .docker_raw/Dockerfile
    image: raw_script
    restart: always